### ISSUE TITLE
Doesn't compile with cargo v1.87 and v1.88

### ISSUE THREAD

**Issue by aolieman** [CoinFabrik/scout-audit#314]
Compilation fails for me, on the `toml v0.8.15` dependency. This version is almost a year old. Perhaps it just needs an update?

```text
error[E0599]: no method named `serialize_field` found for struct `toml_edit::ser::array::SerializeValueArray` in the current scope
    --> /home/alex/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/toml-0.8.15/src/ser.rs:816:24
     |
816  |             self.inner.serialize_field(value).map_err(Error::wrap)
     |                        ^^^^^^^^^^^^^^^ method not found in `SerializeValueArray`
     |
    ::: /home/alex/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde-1.0.204/src/ser/mod.rs:1651:8
     |
1651 |     fn serialize_field<T>(&mut self, value: &T) -> Result<(), Self::Er...
     |        --------------- the method is available for `toml_edit::ser::array::SerializeValueArray` here
     |
     = help: items from traits can only be used if the trait is in scope
help: trait `SerializeTupleStruct` which provides `serialize_field` is implemented but not in scope; perhaps you want to import it
     |
752  +     use serde::ser::SerializeTupleStruct;
     |

error[E0599]: no method named `end` found for struct `toml_edit::ser::array::SerializeValueArray` in the current scope
   --> /home/alex/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/toml-0.8.15/src/ser.rs:820:64
    |
820 |             write_document(self.dst, self.settings, self.inner.end())
    |                                                                ^^^ method not found in `SerializeValueArray`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following traits which provide `end` are implemented but not in scope; perhaps you want to import one of them
    |
752 +     use serde::ser::SerializeMap;
    |
752 +     use serde::ser::SerializeSeq;
    |
752 +     use serde::ser::SerializeStruct;
    |
752 +     use serde::ser::SerializeStructVariant;
    |
      and 3 other candidates

error[E0599]: no method named `serialize_field` found for struct `toml_edit::ser::array::SerializeValueArray` in the current scope
    --> /home/alex/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/toml-0.8.15/src/ser.rs:981:24
     |
981  |             self.inner.serialize_field(value).map_err(Error::wrap)
     |                        ^^^^^^^^^^^^^^^ method not found in `SerializeValueArray`
     |
    ::: /home/alex/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde-1.0.204/src/ser/mod.rs:1651:8
     |
1651 |     fn serialize_field<T>(&mut self, value: &T) -> Result<(), Self::Er...
     |        --------------- the method is available for `toml_edit::ser::array::SerializeValueArray` here
     |
     = help: items from traits can only be used if the trait is in scope
help: trait `SerializeTupleStruct` which provides `serialize_field` is implemented but not in scope; perhaps you want to import it
     |
752  +     use serde::ser::SerializeTupleStruct;
     |

error[E0599]: no method named `end` found for struct `toml_edit::ser::array::SerializeValueArray` in the current scope
   --> /home/alex/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/toml-0.8.15/src/ser.rs:985:46
    |
985 |             write_value(self.dst, self.inner.end())
    |                                              ^^^ method not found in `SerializeValueArray`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following traits which provide `end` are implemented but not in scope; perhaps you want to import one of them
    |
752 +     use serde::ser::SerializeMap;
    |
752 +     use serde::ser::SerializeSeq;
    |
752 +     use serde::ser::SerializeStruct;
    |
752 +     use serde::ser::SerializeStructVariant;
    |
      and 3 other candidates

For more information about this error, try `rustc --explain E0599`.
error: could not compile `toml` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-scout-audit v0.3.8`, intermediate artifacts can be found at `/tmp/cargo-installwTyDDG`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by matiascabello** [comment]
Thanks for submitting this issue! It seems that the latest version of `rustc` has conflicts with some packages.

We have solved the problem with the installation. Feel free to clone the `develop` branch of https://github.com/CoinFabrik/scout-audit, navigate to `apps/cargo-scout-audit` and install it with `cargo install --path .` However, be aware that you may face compilation issues while running Scout on certain projects.

We're working on the definite fix and we'll let you know once it's released in crates.io.

**Comment by aolieman** [comment]
Thanks, it now compiles and installs. I'm still not able to run the develop branch version due to another dependency conflict.

```
$ cargo scout-audit --toolchain
[INFO] Validating CLI arguments...
nightly-2024-07-11
```

Running `cargo scout-audit` on a project fails with:

```
[INFO] Validating CLI arguments...
[INFO] Re-running scout with nightly toolchain...
[INFO] Validating CLI arguments...
[INFO] Getting detector names...
[INFO] Compiling detectors...
[INFO] Running scout...
Warning: `--pipe-stdout` is experimental
Building driver for toolchain `nightly-2024-07-11-x86_64-unknown-linux-gnu`
    Updating crates.io index
     ...
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 18.80s
Checking with toolchain `nightly-2024-07-11-x86_64-unknown-linux-gnu`
error: failed to download `base64ct v1.8.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/base64ct-1.8.0/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.81.0-nightly (154fdac39 2024-07-07)).
  Consider trying a more recent nightly release.
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.
```

**Comment by matiascabello** [comment]
Thanks for the update @aolieman!

We’ve also encountered this issue on certain projects.

We're actively working on a fix to ensure compatibility. We’ll keep you posted as soon as we publish an updated version that resolves this.

Thanks again for your patience and for helping us improve Scout!

**Comment by aolieman** [comment]
> We’ve also encountered this issue on certain projects.

Unsurprising, since `base64ct` is a transitive dependency of `ed25519`. I'd expect all current Soroban projects to encounter this issue.

Thanks for working on a compatibility fix. Would you be able to give an indicative timeline, or steps involved, just to give an impression of the complexity?

**Comment by Helios-vmg** [comment]
The latest version of Scout should have solved this issue. Go ahead and try it and feel free to let us know if you have any other problems.
